version: '3.9'

services:
  bemandiri:
    container_name: bemandiri
    image: mandiri/1.0
    build: ./csharp-crud-api
    ports:
      - "8080:80"
    environment:
      ConnectionStrings__DefaultConnection: "Host=dbmandiri;Database=postgres;Username=postgres;Password=postgres"
    depends_on:
      dbmandiri:
        condition: service_healthy
    x-develop:
      watch:
        - action: rebuild
          path: ./csharp-crud-api
          ignore:
            - node_modules/    
  dbmandiri:
    container_name: dbmandiri
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5  
    volumes:
      - pgmandiri:/var/lib/postgresql/data
      - ./seeds/init.sql:/docker-entrypoint-initdb.d/init.sql
  femandiri:
    container_name: femandiri
    image: femandiri/1.0
    build: ./vueProjectDMCabang
    ports:
      - "8090:8090"
    x-develop:
      watch:
        - action: rebuild
          path: ./vueProjectDMCabang
          ignore:
            - node_modules/
    depends_on:
      dbmandiri:
        condition: service_healthy        

volumes:
  pgmandiri: {}