version: '3.9'

services:
  frontendmandiri:
    container_name: frontendmandiri
    image: frontendmandiri/1.0
    build: .
    ports:
      - "8090:8090"
    x-develop:
      watch:
        - action: rebuild
          path: frontendmandiri
          ignore:
            - node_modules/  