version: '3.9'

services:
  mandiri:
    container_name: mandiri
    image: mandiri/1.0
    build: .
    ports:
      - "8080:80"
    environment:
      ConnectionStrings__DefaultConnection: "Host=dbmandiri;Database=postgres;Username=postgres;Password=postgres"
    depends_on:
      - dbmandiri
  
  dbmandiri:
    container_name: dbmandiri
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdatamandiri:/var/lib/postgresql/data
      - ./seeds/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdatamandiri: {}